---
- name: "Add APT Distribution Package Sources GPG Key"
  apt_key:
    id: "{{ item.key_id }}"
    keyring: "{{ item.keyring | default(omit) }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
    state: present
    url: "{{ item.key_url | default(omit) }}"
  when: ansible_pkg_mgr == 'apt' and item.key_id is defined
  with_items: "{{ pkgsource_present }}"

- name: "Add APT Distribution Package Sources"
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
    codename: "{{ item.codename | default(omit) }}"
    update_cache: "{{ item.update_cache | default('no') }}"
  when: ansible_pkg_mgr == 'apt' and item.repo.startswith('deb')
  with_items: "{{ pkgsource_present }}"
  notify:
    - "update apt cache"

- name: "Remove APT Distribution Package Sources"
  apt_repository:
    repo: "{{ item.repo }}"
    state: absent
  when: ansible_pkg_mgr == 'apt' and item.repo.startswith('deb')
  with_items: "{{ pkgsource_absent }}"
  notify:
    - "update apt cache"

- name: "Remove APT Distribution Package Sources GPG Key"
  apt_key:
    id: "{{ item.key_id }}"
    keyring: "{{ item.keyring | default(omit) }}"
    state: absent
    url: "{{ item.key_url | default(omit) }}"
  when: ansible_pkg_mgr == 'apt' and item.key_id is defined
  # and item.startswith('deb')
  with_items: "{{ pkgsource_absent }}"

# Yum is madly complicated in my opinion. Since I only have very little
# experience with it, I will not make any attempt to provide support
# for it (would most likely end-up being broken anyway)
# If you want to, please contribute, otherwise Yum will likely remain
# unsupported.


# vim: et:sw=2:syntax=yaml:ts=2:
